### ISSUE TITLE
Include LICENSE in sdist

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-xtriggers#6]
cylc-xtriggers will likely become a conda package. Similarly as it was done in metomi-isodatetime, and is being done in cylc-flow, we will need the LICENSE file to be included in the sdist, so we don't need to duplicate the LICENSE file in both this repo and conda-recipe.

See https://github.com/metomi/isodatetime/pull/144 and https://github.com/cylc/cylc-flow/issues/3387 for more.

**Comment by sgaist** [comment]
Hi,

I can take on this one :-)
