### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-xtriggers#8]
Run tests on Travis-CI:

* We should run `pycodestyle` against all Python code.
* `cylc.flow.xtriggers.xrandom` has doctests.
* We should add tests for the other xtriggers in due course.

Note: you can run doctests using pytest by putting the following in a `pytest.ini` file:

```ini
[pytest]
addopts =
    --doctest-modules
```

**Comment by kinow** [comment]
+1 Are you working on this soon, or would you like to add it to hacktoberfest?

**Comment by oliver-sanders** [comment]
Meant to add the hacktoberfest label!

**Comment by ytturi** [comment]
I'm going to work on this 👍 
PR incoming soon 😃
